"""empty message

Revision ID: 79e1dc0b0cc2
Revises: 6d752623ad0f
Create Date: 2025-05-02 10:47:54.867823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e1dc0b0cc2'
down_revision = '6d752623ad0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_planet',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    op.create_table('user_spaceship',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spaceship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spaceship_id'], ['spaceships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'spaceship_id')
    )
    op.create_table('user_warrior',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warrior_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrior_id'], ['warriors.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'warrior_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_warrior')
    op.drop_table('user_spaceship')
    op.drop_table('user_planet')
    # ### end Alembic commands ###
